### ISSUE TITLE
Simplify the creation of policies: create a library

### ISSUE THREAD

**Issue by kkaempf** [kubewarden/policy-sdk-rust#2]
Policies have a lot of common code, we should create a library to reduce the boilerplate and make it easier to write new policies and read existing ones.

# Acceptance criteria

* [x] Provide SDK
* [ ] Update official docs: explain how to write policies using the SDK

**Comment by flavio** [comment]
I've handled the Rust SDK, @ereslibre is handling the Go one

**Comment by flavio** [comment]
The policy SDK is done, we still need to write documentation about it. I'll create a dedicated card about that on the docs repo
